@MiniCRM_Api_HostAddress = https://localhost:7238

POST {{MiniCRM_Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "Lisa Wilson",
  "email": "lisa@example.com"
}

###
GET {{MiniCRM_Api_HostAddress}}/api/customers
Accept: application/json