@MiniCRM_Api_HostAddress = https://localhost:7238

POST {{MiniCRM_Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "Lisa Wilson",
  "email": "lisa@example.com"
}

###
GET {{MiniCRM_Api_HostAddress}}/api/customers
Accept: application/json

###
POST {{MiniCRM_Api_HostAddress}}/api/customers/1/notes
Content-Type: application/json

{
  "text": "Called customer about renewal."
}

###
GET {{MiniCRM_Api_HostAddress}}/api/customers/1/details

###
PUT {{MiniCRM_Api_HostAddress}}/api/customers/1
Content-Type: application/json

{
  "name": "John Smith Updated",
  "email": "john.updated@example.com"
}

### Get paged customers
GET {{MiniCRM_Api_HostAddress}}/api/customers?page=1&pageSize=100